id: 13b4c280396e407e8246865b1865e1d3
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_83-The_Questions_of_Bhadrapala_the_Merchant-v1
  language: en
  author: ''
  volume: {}
